version: 2

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs


sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt