version: 2

python:
  version: "3.8"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - requirements: docs/requirements.txt

sphinx:
  builder: html
  fail_on_warning: true

python:
   install:
   - requirements: docs/requirements.txt
